name: 🐛 Bug Report
description: File a bug report to help us improve uzp-cli
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: ["hungnguyen18"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! 🙏
        
        **Before submitting:**
        - Search existing issues to avoid duplicates
        - Make sure you're using the latest version of uzp-cli

  - type: input
    id: version
    attributes:
      label: UZP-CLI Version
      description: What version of uzp-cli are you running?
      placeholder: "e.g., v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Ubuntu/Debian)
        - Linux (RHEL/CentOS)
        - Linux (Arch)
        - Linux (Other)
        - Windows 10
        - Windows 11
        - Other
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe the expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Describe what actually happened..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command `uzp ...`
        2. See error
        3. ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Output/Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Any additional information that might help..."

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched for existing issues before creating this one
          required: true
        - label: I am using the latest version of uzp-cli
          required: true
        - label: I have included all the requested information above
          required: true 