package cmd

import (
	"fmt"
	"os"
	"sort"
	"syscall"

	"github.com/spf13/cobra"
	"golang.org/x/term"
)

var projectName string

var injectCmd = &cobra.Command{
	Use:   "inject",
	Short: "Export project secrets as .env format",
	Long: `📄 Export Project Secrets as .env Format

Export all secrets for a specific project in environment variable format.
This is useful for loading secrets into applications or CI/CD pipelines.

The output format follows .env file conventions:
  • Keys are converted to UPPERCASE
  • Non-alphanumeric characters become underscores
  • Includes helpful comments with project name

USAGE:
  uzp inject --project PROJECT_NAME [> output_file]

EXAMPLES:
  # Export to .env file (recommended)
  uzp inject --project myapp > .env
  
  # Export to custom file  
  uzp inject -p backend > backend.env
  
  # View output on screen
  uzp inject --project myapp
  
  # Use in docker-compose
  uzp inject -p webapp > .env && docker-compose up

OUTPUT FORMAT:
  # Environment variables for project: myapp
  # Generated by uzp
  
  API_KEY=your_secret_value
  DATABASE_URL=your_db_connection`,
	RunE: func(cmd *cobra.Command, args []string) error {
		// Validate arguments FIRST before prompting for password
		if projectName == "" {
			return fmt.Errorf(`❌ Missing required project name

USAGE:
  uzp inject --project PROJECT_NAME [> output_file]

EXAMPLES:
  uzp inject --project myapp > .env
  uzp inject -p backend > backend.env

💡 TIP: Use 'uzp list' to see available projects`)
		}

		// Check if vault is unlocked, auto-unlock if needed
		if !vault.IsUnlocked() {
			fmt.Fprint(os.Stderr, "🔒 Vault is locked. Enter master password: ")
			password, err := term.ReadPassword(int(syscall.Stdin))
			if err != nil {
				return fmt.Errorf("failed to read password: %w", err)
			}
			fmt.Fprintln(os.Stderr) // New line after password

			if err := vault.Unlock(string(password)); err != nil {
				return fmt.Errorf("❌ Invalid master password. Please try again")
			}

			// Clear password from memory
			for i := range password {
				password[i] = 0
			}
		}

		// Get project secrets
		secrets, err := vault.GetProjectSecrets(projectName)
		if err != nil {
			return fmt.Errorf(`❌ Project '%s' not found

💡 SUGGESTIONS:
  • Check spelling: uzp list (shows all projects)
  • Create project: uzp add (add first secret for this project)
  • Search projects: uzp search %s

Available commands:
  uzp list                    # Show all projects
  uzp add                     # Add new secret
  uzp search KEYWORD          # Search projects/keys`, projectName, projectName)
		}

		// Sort keys for consistent output
		keys := make([]string, 0, len(secrets))
		for key := range secrets {
			keys = append(keys, key)
		}
		sort.Strings(keys)

		// Output in .env format
		fmt.Printf("# Environment variables for project: %s\n", projectName)
		fmt.Printf("# Generated by uzp\n\n")

		for _, key := range keys {
			// Convert key to uppercase and replace non-alphanumeric chars with underscore
			envKey := convertToEnvKey(key)
			fmt.Printf("%s=%s\n", envKey, secrets[key])
		}

		return nil
	},
}

func init() {
	injectCmd.Flags().StringVarP(&projectName, "project", "p", "", "Project name to export secrets from")
}

// convertToEnvKey converts a key to environment variable format
func convertToEnvKey(key string) string {
	result := make([]byte, 0, len(key))

	for i := 0; i < len(key); i++ {
		c := key[i]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			// Convert to uppercase if lowercase
			if c >= 'a' && c <= 'z' {
				c = c - 32
			}
			result = append(result, c)
		} else {
			// Replace non-alphanumeric with underscore
			result = append(result, '_')
		}
	}

	return string(result)
}
